networks:
  photopro.net:
    driver: bridge

services:
  # Service d'infra et messagerie RabbitMQ
  rabbitmq:
    image: rabbitmq:4-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 8s
      timeout: 30s
      retries: 3
    networks:
      - photopro.net
    volumes:
      - ./rabbitmq.photo:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: photo
      RABBITMQ_DEFAULT_PASS: photo
    entrypoint: /bin/sh
    command: -c "if [ -f /var/lib/rabbitmq/.erlang.cookie ]; then chmod 600 /var/lib/rabbitmq/.erlang.cookie; fi && exec docker-entrypoint.sh rabbitmq-server"

  mailcatcher:
    build:
      context: build
      dockerfile: mailcatcher.Dockerfile
    networks:
      - photopro.net

  # Gateways
  gateway_backoffice:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '${PORT_GATEWAY_BACKOFFICE}:80'
    volumes:
      - ./back/gateway-backoffice:/var/php
    working_dir: /var/php
    networks:
      - photopro.net
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

  gateway_frontoffice:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '${PORT_GATEWAY_FRONTOFFICE}:80'
    volumes:
      - ./back/gateway-frontoffice:/var/php
    working_dir: /var/php
    networks:
      - photopro.net
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

  # Microservices métiers
  # Service Galerie
  api_galerie:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    volumes:
      - ./back/app-galerie:/var/php
    env_file:
      - ./back/app-galerie/config/.env
    working_dir: /var/php
    networks:
      - photopro.net
    depends_on:
      galerie.db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    command: sh -c "composer install --ignore-platform-reqs || composer update --no-interaction --ignore-platform-reqs && php -S 0.0.0.0:80 -t /var/php/public"

  # Service Auth / Identité
  api_auth:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    volumes:
      - ./back/app-auth:/var/php
    env_file:
      - ./back/app-auth/config/.env
    working_dir: /var/php
    networks:
      - photopro.net
    depends_on:
      auth.db:
        condition: service_started
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

  # Service Storage
  api_storage:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    container_name: api_storage
    volumes:
      - ./back/app-storage:/var/php
    working_dir: /var/php
    command: sh -c "composer config process-timeout 3600 && composer install && php -S 0.0.0.0:80 -t public"
    environment:
      - S3_INTERNAL_ENDPOINT=http://S3:8333
      - S3_EXTERNAL_ENDPOINT=${S3_EXTERNAL_ENDPOINT}
      - S3_REGION=seaweedFS
      - S3_ACCESS_KEY=GHIJKL
      - S3_SECRET_KEY=789012
      - S3_BUCKET=photopro-galeries
    networks:
      - photopro.net
    depends_on:
      - S3

  # Service Notif
  app-mail:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    volumes:
      - ./back/app-mail:/var/php
    env_file:
      - ./back/app-mail/config/.env
    working_dir: /var/php
    networks:
      - photopro.net
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: sh -c "composer install && php consumer.php || tail -f /dev/null"

  # BDs
  galerie.db:
    image: 'postgres:latest'
    env_file: ./back/app-galerie/config/.env
    networks:
      - photopro.net
    volumes:
      - ./sql/schema/galerie.schema.sql:/docker-entrypoint-initdb.d/03.schema.sql
      - ./sql/data/galerie.data.sql:/docker-entrypoint-initdb.d/04.data.sql

  auth.db:
    image: 'postgres:latest'
    env_file: ./back/app-auth/config/.env
    networks:
      - photopro.net
    volumes:
      - ./sql/schema/auth.schema.sql:/docker-entrypoint-initdb.d/01.schema.sql
      - ./sql/data/auth.data.sql:/docker-entrypoint-initdb.d/02.data.sql

  adminer:
    image: adminer
    ports:
      - "${PORT_ADMINER}:8080"
    networks:
      - photopro.net

  # Frontend Vue.js
  app-vue:
    image: node:22-alpine
    ports:
      - "${PORT_FRONTEND}:5173"
    volumes:
      - ./app-vue:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - photopro.net
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    command: sh -c "npm install || true && npm run dev -- --host"

  # Stockage SeaweedFS (Compatible S3)
  S3:
    image: chrislusf/seaweedfs:latest
    networks:
      - photopro.net
    command: "server -dir=/data -s3 -s3.port=8333 -s3.config=/etc/seaweedfs/s3.json"
    volumes:
      - ./S3/data:/data
      - ./S3:/etc/seaweedfs
