@startuml
package "Service Authentification / Identité" {
    class Utilisateur {
        - id : UUID <<PK>>
        - email : String
        - mot_de_passe_hash : String
        - role : String
    }
}

package "Service Galerie (Domaine)" {
    class Photographe {
        - id : UUID <<PK>>
        - utilisateur_id : UUID <<FK>>
        - nom : String
    }

    class Galerie {
        - id : UUID <<PK>>
        - titre : String
        - description : String
        - est_privee : Boolean
        - clef_acces : String <<Key>>
        - date_creation : DateTime
    }

    class Photo {
        - id : UUID <<PK>>
        - clef_stockage : String <<S3 Key>>
        - titre : String
        - date_upload : DateTime
    }

    class Commentaire {
        - id : UUID <<PK>>
        - nom_visiteur : String
        - texte : String
        - date_publication : DateTime
    }
}

' Relations inter-services (conceptuelles)
Utilisateur "1" -right- "1" Photographe : est lié à >

' Relations internes au domaine
Photographe "1" -- "0..*" Galerie : possède >
Galerie "1" *-- "0..*" Photo : contient >
Photo "1" -- "0..*" Commentaire : possède >

@enduml