import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../providers/gallery_providers.dart';
import '../../core/api/api_config.dart';

class GalleryDetailScreen extends ConsumerWidget {
  final String galleryId;
  const GalleryDetailScreen({super.key, required this.galleryId});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final photosAsync = ref.watch(galleryPhotosProvider(galleryId));

    return Scaffold(
      appBar: AppBar(title: const Text('Photos de la Galerie')),
      body: photosAsync.when(
        data: (paginated) {
          if (paginated.items.isEmpty) {
            return const Center(child: Text("Cette galerie est vide pour le moment."));
          }
          return GridView.builder(
            padding: const EdgeInsets.all(8),
            gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 3,
              crossAxisSpacing: 8,
              mainAxisSpacing: 8,
            ),
            itemCount: paginated.items.length,
            itemBuilder: (context, index) {
              final photo = paginated.items[index];
              
              // We replace 10.0.2.2 or localhost with our known S3 URL mapping if testing locally
              // Because photo.storageUrl resolves the S3 URL generated by the backend
              String imageUrl = photo.storageUrl;

              // Handle improperly formatted URLs containing another http inside them
              final httpIndex = imageUrl.indexOf('http', 4);
              if (httpIndex != -1) {
                imageUrl = imageUrl.substring(httpIndex);
              } else if (Theme.of(context).platform == TargetPlatform.android && imageUrl.contains('localhost')) {
                imageUrl = imageUrl.replaceAll('localhost', '10.0.2.2');
              }

              return InkWell(
                onTap: () => context.push('/gallery/$galleryId/photo/${photo.remoteId}'),
                child: Hero(
                  tag: 'photo_${photo.remoteId}',
                  child: Image.network(
                    imageUrl,
                    fit: BoxFit.cover,
                    errorBuilder: (_, __, ___) => Container(
                      color: Colors.grey[300],
                      child: const Icon(Icons.broken_image),
                    ),
                  ),
                ),
              );
            },
          );
        },
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (err, _) => Center(child: Text('Erreur: $err')),
      ),
    );
  }
}
